version: '3.7'

services:
  api:
    image: node:10.16.0-alpine
    volumes:
      - ./api/:/api/
      - /api/node_modules
    working_dir: /api
    command: sh -c "npm install && npm run dev"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"

  db_seed:
    image: mongo
    links:
      - db
    volumes:
      - ./seed:/seed
    command:
      - /seed/import.sh
